version = "1.0"
[main]
services = ["__APP__"]

[main.main]

[main.main.cloud_addresses]
ask.en = "IP address of the cloud machine"
ask.fr = "Adresse IP de la machine cloud"
help.en = "You get this information when you configure the cloud machine with the setup instructions described above"
help.fr = "Tu récupères cette information en configurant la machine cloud comme décrit ci-dessus"
type = "string"
pattern.regexp = "^[0-9a-f:.,]+$"
bind = "addresses_str:__INSTALL_DIR__/home.toml"

[main.main.link_token]
ask.en = "Configuration secret token"
ask.fr = "Clé de configuration secrète"
help.en = "You get this information when you configure the cloud machine with the setup instructions described above"
help.fr = "Tu récupères cette information en configurant la machine cloud comme décrit ci-dessus"
type = "string"
redact = true
pattern.regexp = "^[0-9a-f]+$"
bind = "token:__INSTALL_DIR__/home.toml"

[main.main.expose_web]
ask.en = "Expose Web ports (80 and 443)"
ask.fr = "Exposer les ports Web (80 et 443)"
help.en = "This allows Internet users to see your hosted Yunohost apps"
help.fr = "Ceci permet aux utilisateurs Internet de voir tes applications Yunohost"
type = "boolean"
default = 1
yes = "true"
no = "false"
bind = "web_ports:__INSTALL_DIR__/home.toml"

[main.main.expose_ssh]
ask.en = "Expose SSH port (22)"
ask.fr = "Exposer le port SSH (22)"
help.en = "This allows Internet users to see your SSH server"
help.fr = "Ceci permet aux utilisateurs Internet de voir ton seveur SSH"
type = "boolean"
default = 0
yes = "true"
no = "false"
bind = "ssh_port:__INSTALL_DIR__/home.toml"

[main.main.expose_email]
ask.en = "Expose email ports (25, 587 and 994)"
ask.fr = "Exposer les ports mail (25, 587 et 994)"
help.en = "This allows Internet users to see your email server"
help.fr = "Ceci permet aux utilisateurs Internet de voir ton seveur mail"
type = "boolean"
default = 0
yes = "true"
no = "false"
bind = "email_ports:__INSTALL_DIR__/home.toml"

[main.main.more_ports]
ask.en = "A comma-separated list of other TCP ports to expose"
ask.fr = "Une liste separé par virgule d'autres ports TCP à exposer"
help.en = "Leaving this empty is probably what you need"
help.fr = "Tu peux laisser ce champ vide, c'est probablement ce qu'il te faut"
type = "string"
optional = true
pattern.regexp = "^[0-9,]+$"
bind = "more_ports_str:__INSTALL_DIR__/home.toml"
